# Self-Hosted Github Action Runners on Openstack via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml.html
runners:
  - name: openstack-runner
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: gpu_large
    # The machine image to use for creating VM
    machine_image: ubuntu-focal-nvidia-14112022
    region: RegionOne
    # Path of the relevant workflow file
    labels:
      - cirun-runner
