#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

echo "############################################################"
echo "# Install Mellanox OFED for Ubuntu OS with kernel support  #"
echo "############################################################"

mkdir /tmp/ofed_install
mount -o ro,loop /tmp/MLNX* /tmp/ofed_install
unset ARCH
CHROOT_KERNEL=$(uname -r)

echo "Release"
echo "============================================"
cat /etc/*release
echo "============================================"
echo "Current Kernel: $CHROOT_KERNEL"
echo "============================================"
# Assume HOST and Image Kernel is same
#sudo add-apt-repository ppa:cappelikan/ppa
#sudo apt update
#sudo apt upgrade
#sudo apt install linux-image-$CHROOT_KERNEL -y
#sudo apt install linux-headers-$CHROOT_KERNEL -y

/tmp/ofed_install/mlnxofedinstall -k ${CHROOT_KERNEL} \
  --without-fw-update \
  --add-kernel-support \
  --force \
  --kernel-sources /lib/modules/5.15.0-50-generic/build \
  -vvv

export ARCH=amd64
rm -f /etc/udev/rules.d/82-net-setup-link.rules
rm -f /etc/udev/rules.d/90-ib.rules
umount /tmp/ofed_install
