#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail


echo "#############################################################"
echo "# CUDA Installation                                         #"
echo "#############################################################"

## comparing chroot kernel with host kernel
#CHROOT_KERNEL=$(rpm -q --queryformat "%{installtime} %{version}-%{release}.%{arch}\n" kernel | sort -nr | sed -n 1p | cut -d' ' -f2)
#HOST_KERNEL=$(uname -r)
#if [ "$CHROOT_KERNEL" != "$HOST_KERNEL" ]; then
#	"ERROR: kernel mismatch!"
#	exit 1
#fi

echo "Installing linux headers"
sudo apt-get install linux-headers-"$(uname -r)" -y

# download cuda run file installer for ubuntu

mkdir -p /tmp/cuda 
cd /tmp/cuda

if [ -n "${DIB_CUDA_URL}" ]; then
    start=$(date +%s)
    wget -nv "$DIB_CUDA_URL"
    end=$(date +%s)
    runtime=$((end-start))
    echo "Time taken to Download CUDA: $runtime"
else
    echo "ERROR: DIB_CUDA_URL is not set."
fi

# Install cuda
echo "Installing CUDA"
unset ARCH
start=$(date +%s)
sh cuda_* --driver --toolkit --silent
end=$(date +%s)
runtime=$((end-start))
echo "Time taken to Install CUDA: $runtime"

# Clean
echo "Cleanup"
export ARCH=amd64
rm -Rf /tmp/cuda
echo "Done"
