#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail


echo "#############################################################"
echo "# CUDA Installation                                         #"
echo "#############################################################"

## comparing chroot kernel with host kernel
#CHROOT_KERNEL=$(rpm -q --queryformat "%{installtime} %{version}-%{release}.%{arch}\n" kernel | sort -nr | sed -n 1p | cut -d' ' -f2)
#HOST_KERNEL=$(uname -r)
#if [ "$CHROOT_KERNEL" != "$HOST_KERNEL" ]; then
#	"ERROR: kernel mismatch!"
#	exit 1
#fi

# download cuda run file installer for ubuntu

mkdir -p /tmp/cuda 
cd /tmp/cuda

if [ -n "${DIB_CUDA_URL}" ]; then
    wget -nv $DIB_CUDA_URL
else
    echo "ERROR: DIB_CUDA_URL is not set."
fi

# Install cuda
unset ARCH
sh cuda_* --driver --toolkit --silent

# clean
export ARCH=amd64
rm -Rf /tmp/cuda
