#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail


echo "#############################################################"
echo "# CUDA Installation                                         #"
echo "#############################################################"

## comparing chroot kernel with host kernel
#CHROOT_KERNEL=$(rpm -q --queryformat "%{installtime} %{version}-%{release}.%{arch}\n" kernel | sort -nr | sed -n 1p | cut -d' ' -f2)
#HOST_KERNEL=$(uname -r)
#if [ "$CHROOT_KERNEL" != "$HOST_KERNEL" ]; then
#	"ERROR: kernel mismatch!"
#	exit 1
#fi

echo "Installing linux headers"
sudo apt-get install linux-headers-"$(uname -r)" -y

echo "Installing Nvidia Drivers"
echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y -q
DEBIAN_FRONTEND=noninteractive sudo apt update
DEBIAN_FRONTEND=noninteractive sudo apt upgrade -y
DEBIAN_FRONTEND=noninteractive sudo apt install nvidia-driver-515 -y
echo "Done"
