name: Build Ubuntu NVIDIA Image

on: push

env:
  OUTPUT_IMAGE_PATH: /tmp/ubuntu-nvidia

jobs:
  build:
    runs-on: "cirun-runner--${{ github.run_id }}"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        env:
          CONDA: /home/runnerx/miniconda3
        with:
          python-version: "3.10"
          miniconda-version: "latest"

      - name: Set output image path
        run: |
          cat .env >> $GITHUB_ENV
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt-get install qemu-utils -y
          pip install -r requirements.txt
          sudo apt install python3-pip

      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.13


      - name: Run disk image builder
        shell: bash -el {0}
        run: |
          echo "OUTPUT_IMAGE_PATH: $OUTPUT_IMAGE_PATH"
          bash run.sh
