name: Build Ubuntu NVIDIA Image

on: push

env:
  OUTPUT_IMAGE_PATH: /tmp/ubuntu-nvidia

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"

      - name: Set output image path
        run: |
#          timestamp=$(date +%s)
#          echo "OUTPUT_IMAGE_PATH=/tmp/ubuntu-nvidia-$timestamp" >> $GITHUB_ENV
          cat .env >> $GITHUB_ENV
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt-get install qemu-utils -y
          pip install -r requirements.txt

      - name: Run disk image builder
        shell: bash -el {0}
        run: |
          echo "OUTPUT_IMAGE_PATH: $OUTPUT_IMAGE_PATH"
          bash run.sh
